server {
    listen 80;
    server_name localhost;
    
    # Raiz do site (onde estarão seus arquivos HTML/PHP)
    root /var/www/html;
    index index.html index.php;

    # 1. Tenta servir o arquivo solicitado. Se não achar, joga 404.
    location / {
        try_files $uri $uri/ =404;
    }

    # 2. Configuração para processar scripts PHP
    location ~ \.php$ {
        fastcgi_pass php:9000; # Envia para o container 'php'
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloqueia acesso a arquivos ocultos (como .env se estivesse na pasta pública)
    location ~ /\.ht {
        deny all;
    }
}